version: "3.3"

services:
  mongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=12Sqecd34!
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - internal

  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=12Sqecd34!
    ports:
      - 6379:6379
    networks:
      - internal
  
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq/
    #   - rabbitmq_log:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "user"
    networks:
      - internal
  
  # pubsubRedis:
  #   image: redis:alpine
  #   environment:
  #     - REDIS_PASSWORD=12Sqecd34!
  #     - REDIS_PORT=6380
  #   ports:
  #     - 6380:6380
  #   networks:
  #     - internal
      
networks:
  internal:

volumes:
  data:
